#!/bin/bash

or1k_utils=$HOME/work/openrisc/or1k-utils
rootfs=output/images/rootfs.cpio.gz

make $@


if [ -f $rootfs ]; then

  echo "Copying rootfs.cpio.gz to $or1k_utils/litex/tftpd/"
  ls -lh output/images/
  cp $rootfs $or1k_utils/litex/tftpd/
  # Update rootfs size in the device tree
  make -C $or1k_utils/litex/tftpd
else

  echo "Skipping copy, missing $rootfs"
fi
