#!/bin/bash

TOOLCHAIN=${TOOLCHAIN:-or1k-linux-}
LINUX_SRC=${LINUX_SRC:-$HOME/work/linux}

BUILDDIR=${BUILDDIR:-$HOME/work/openrisc}
OR1K_UTILS=${OR1K_UTILS:-$BUILDDIR/or1k-utils}
BUSYBOX=${BUSYBOX:-$BUILDDIR/busybox-rootfs}
OPENADK=${OPENADK:-$BUILDDIR/openadk}

litextftpd=$OR1K_UTILS/litex/tftpd
openadk_source="$OPENADK/target_qemu-or1k_uclibc-ng/qemu-or1k-uclibc-ng-initramfspiggyback_list"
busybox_source="$BUSYBOX/initramfs $BUSYBOX/initramfs.devnodes"

# Select one of these to choose your preferred initramfs we use for de0nano and
# or1ksim, but no longer for qemu as for qemu we just pass in the qcow2 rootfs.
# Also on litex we have an sdcard for the rootfs.
if ! grep -q '^CONFIG_\(LITEX\|VIRT\)_' $LINUX_SRC/.config; then
  #INITRAMFS_SOURCE=$openadk_source
  INITRAMFS_SOURCE=$busybox_source
  echo "Enabling INITRAMFS_SOURCE=$INITRAMFS_SOURCE for non litex/virt build"
fi

run() {
  echo "exec: $@"
  "$@"
}

(
  # Getting a bunch of perl warnings with en_US.utf8
  export LC_ALL=en_US.UTF-8

  cd $LINUX_SRC
  run make -j12 LC_ALL=en_US.UTF-8 ARCH=openrisc \
     CROSS_COMPILE=${TOOLCHAIN} \
     CONFIG_INITRAMFS_SOURCE="$INITRAMFS_SOURCE" \
     $@

  if [ -f arch/openrisc/boot/vmlinux.bin ] && grep -q 'CONFIG_LITEX=y' .config ; then
    run cp arch/openrisc/boot/vmlinux.bin $litextftpd/boot.bin
  fi
#  echo "Generating initramfs.cpio.gz ..."
#  ./usr/gen_initramfs.sh -o initramfs.cpio -u squash -g squash $initramfs_source
#  gzip -f initramfs.cpio
)


# make ARCH=openrisc INSTALL_HDR_PATH=/opt/shorne/software/or1k-linux headers_install
