#!/bin/bash

or1k_utils=$HOME/work/openrisc/or1k-utils
openadk=$HOME/work/openrisc/openadk
hdmi2usb=$HOME/work/litex/HDMI2USB-litex-firmware
litextftpd=$or1k_utils/litex/tftpd

openadk_source="$openadk/target_qemu-or1k_uclibc-ng/qemu-or1k-uclibc-ng-initramfspiggyback_list"
or1k_utils_source="$or1k_utils/initramfs $or1k_utils/initramfs.devnodes"

#toolchain=or1k-elf-
#toolchain=or1k-linux-musl-
toolchain=or1k-linux-

# Select one of these to choose your preferred initramfs
# we use for or1ksim, but no longer for qemu as for qemu we just
# passin the initrd.
#initramfs_source=$or1k_utils_source
#initramfs_source=$openadk_source

run() {
  echo "exec: $@"
  "$@"
}

(
  # Getting a bunch of perl warnings with en_US.utf8
  export LC_ALL=en_US.UTF-8

  cd $HOME/work/linux
  run make -j12 LC_ALL=en_US.UTF-8 ARCH=openrisc \
     CROSS_COMPILE=${toolchain} \
     CONFIG_INITRAMFS_SOURCE="$initramfs_source" \
     $@

  if [ -f arch/openrisc/boot/vmlinux.bin ] && grep -q 'CONFIG_LITEX=y' .config ; then
    run cp arch/openrisc/boot/vmlinux.bin $litextftpd/boot.bin
  fi
#  echo "Generating initramfs.cpio.gz ..."
#  ./usr/gen_initramfs.sh -o initramfs.cpio -u squash -g squash $initramfs_source
#  gzip -f initramfs.cpio
)


#run mkdir -p $hdmi2usb/build/arty_net_or1k/software/linux
#run cp arch/openrisc/boot/vmlinux.bin $hdmi2usb/build/arty_net_or1k/software/linux/firmware.bin
# make ARCH=openrisc INSTALL_HDR_PATH=/opt/shorne/software/or1k-linux headers_install
