#!/bin/bash

set -e # FAIL FAST
set -x # DEBUG

# These are the commands to create our qemu qcow image
# from the openrisc buildroot ext2 disk image.

SCRIPT_PATH=`dirname $0`

BUILDDIR=${BUILDDIR:-$HOME/work/openrisc}
BUILDROOT_SRC=${BUILDROOT_SRC:-$BUILDDIR/buildroot}
QEMU_SRC=${QEMU_SRC:-$BUILDDIR/qemu}
OUTPUT=${OUTPUT:-$BUILDDIR/buildroot-rootfs}

qcow_img=$OUTPUT/qemu-fs-or1k-$(date +'%Y%m%d').qcow2
extfs_img=$BUILDROOT_SRC/output/images/rootfs.ext2

mkdir -p $OUTPUT

if [ ! -f ${extfs_img} ] ; then
  echo "E2FS Image: $extfs_img doesn't exist.  Can't make image, make buidroot first."
  exit 1
fi

if [ ! -f ${qcow_img} ] ; then
  $QEMU_SRC/build/qemu-img create -o size=8G -f qcow2 $qcow_img

  # Mound image as device
  sudo modprobe nbd
  sudo qemu-nbd -c /dev/nbd0  $qcow_img

  # use FDISK to partition
  sudo sfdisk /dev/nbd0 < $SCRIPT_PATH/qemu-or1k-img.part

  # Make swap image
  sudo mkswap /dev/nbd0p1

  # Write ext4 image
  sudo dd if=$extfs_img of=/dev/nbd0p2
  sudo resize2fs /dev/nbd0p2

  # Unmount image
  sync
  sudo qemu-nbd -d /dev/nbd0
else
  echo "Image: $qcow_img already exists, doing nothing."
  exit 1
fi
