#! /bin/sh

log() {
#  echo $(date +"%Y-%m-%dT%H:%M:%S.000") " " $@
   true
}

log "Mounting filesystems"
mount -a

# set hostname
log "Setting hostname"
hostname openrisc &

#remount everything, read/write
log "Re-mounting read/write"
mount -o remount,rw /

# clear ethernet's IP
#echo "Bringing up eth0"
#ifconfig eth0 10.1.1.3
#ifconfig eth0 up

#setup dhcp
#echo "Launching udhcpc"
#/sbin/udhcpc -n -q -s /usr/share/udhcpc/default.script

# create some dirs to avoid warning messages
log "Making aux directories"
mkdir -p /var/run && \
 mkdir -p /etc/network/if-up.d && \
 mkdir -p /etc/network/if-pre-up.d &

# make home directory for root user
mkdir -p /root &

# telnetd requires this
log "Mounting /dev/pts"
mkdir -p /dev/pts && \
 mount -t devpts none /dev/pts &

log "Mounting /dev/shm"
mkdir -p /dev/shm && \
 mount -t tmpfs none /dev/shm &

log "Configuring loopback device"
#ifconfig lo 127.0.0.1
ifup lo &
log "Brining up eth0"
ifconfig eth0 10.9.0.12 netmask 255.255.255.0
route add default gw 10.9.0.100

# inetd startup
log "Launching inetd"
inetd &

